// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//   sqlc-gen-java 0.0.7

package com.example.postgresql;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NonNull;

@Generated("io.github.tandemdude.sqlc-gen-java")
public class Queries {
    private final java.sql.Connection conn;

    public Queries(java.sql.Connection conn) {
        this.conn = conn;
    }


    private static final String findRunnableJobs = """
        -- name: FindRunnableJobs :many
        SELECT filename, retry_count
        FROM video_jobs
        WHERE status = 'PENDING'
          AND retry_count < 5
        """;

    public record FindRunnableJobsRow(
        @NonNull String filename,
        int retryCount
    ) {}

    public List<FindRunnableJobsRow> findRunnableJobs() throws SQLException {
        var stmt = conn.prepareStatement(findRunnableJobs);

        var results = stmt.executeQuery();
        var retList = new ArrayList<FindRunnableJobsRow>();
        while (results.next()) {
            var ret = new FindRunnableJobsRow(
                results.getString(1),
                results.getInt(2)
            );
            retList.add(ret);
        }

        return retList;
    }

    private static final String incrementRetry = """
        -- name: IncrementRetry :exec
        UPDATE video_jobs
        SET retry_count = retry_count + 1,
            updated_at = now()
        WHERE filename = ?
        """;

    public void incrementRetry(
        @NonNull String filename
    ) throws SQLException {
        var stmt = conn.prepareStatement(incrementRetry);
        stmt.setString(1, filename);

        stmt.execute();
    }

    private static final String lockJob = """
        -- name: LockJob :exec
        UPDATE video_jobs
        SET status = 'PROCESSING',
            updated_at = now()
        WHERE filename = ?
          AND status = 'PENDING'
        """;

    public int lockJob(
        @NonNull String filename
    ) throws SQLException {
        var stmt = conn.prepareStatement(lockJob);
        stmt.setString(1, filename);

        stmt.execute();
        return 0;
    }

    private static final String upsertVideoJob = """
        -- name: UpsertVideoJob :exec
        INSERT INTO video_jobs (filename, status)
        VALUES (?, ?)
            ON CONFLICT (filename)
        DO UPDATE SET
            status = EXCLUDED.status,
                   updated_at = now()
        """;

    public void upsertVideoJob(
        @NonNull String filename,
        @NonNull String status
    ) throws SQLException {
        var stmt = conn.prepareStatement(upsertVideoJob);
        stmt.setString(1, filename);
        stmt.setString(2, status);

        stmt.execute();
    }
}
